export const INIT_DEFAULT_LIST = 'INIT_DEFAULT_LIST',
  CHANGE_CURRENTTIME = 'CHANGE_CURRENTTIME',
  SET_DURATION = 'SET_DURATION',
  SET_EM = 'SET_EM',
  CHANGE_PLAYSTATUS = 'CAHNGE_PLAYSTATUS',
  SET_STARTCOUNTTIME = 'SET_STARTCOUNTTIME'
